### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by bosr** [d99kris/heapusage#2]
Hi,

Many thanks for `heapusage`, it's very nice!

Would you mind adding a `1.0` tag to the current commit so that GitHub creates a zip/tar.gz release that we can reference for packaging or else?

Thanks in advance

**Comment by bosr** [comment]
I have created a Homebrew tap (https://github.com/bosr/homebrew-heapusage) for hosting the formula, as Homebrew won't include it before it has more GitHub stars.

**Comment by d99kris** [comment]
Hi @bosr 
Thanks for the positive feedback and also for making it easier to install `heapusage` by creating a Homebrew tap!
Sure, I've created a v1.0 release now: https://github.com/d99kris/heapusage/releases/tag/v1.0

**Comment by d99kris** [comment]
Btw, I'm not too familiar with brew (other than installing stuff once in a while). Once your brew recipe is pointing to the v1.0 release, what would be a good way for me to share it in the README of `heapusage`? Adding installation instructions like this?
```
brew tap bosr/homebrew-heapusage
brew install
```

**Comment by bosr** [comment]
Hi @d99kris,

You're more than welcome, I think this is awesome work. Thanks for the release, I have just updated the formula.

Regarding the tap, yes that would be like this:

    brew tap bosr/homebrew-heapusage
    brew install heapusage

or simply

    brew install bosr/homebrew-heapusage/heapusage

Either way.
Cheers
