### ISSUE TITLE
Support of C++

### ISSUE THREAD

**Issue by romintomasetti** [d99kris/heapusage#7]
Heapusage is a great tool, and at the time of writing supports partially ``c++``.

When I add ``std::cout`` to the ``tests/ex003.cpp`` file, it starts raising leaks that are not raised by ``valgrind``.

```bash
==215590== Heapusage - https://github.com/d99kris/heapusage
==215590== 
==215590== HEAP SUMMARY:
==215590==     in use at exit: 1056 bytes in 2 blocks
==215590==   total heap usage: 12 allocs, 10 frees, 1318 bytes allocated
==215590==    peak heap usage: 1272 bytes allocated
==215590== 
==215590== 1024 bytes in 1 block(s) are lost, originally allocated at:
==215590==    at 0x00007fcbd0e90dc2: malloc + 53
==215590==    at 0x00007fcbd0ae3e84: _IO_file_doallocate + 148
==215590==    at 0x00007fcbd0af4050: _IO_doallocbuf + 80
==215590==    at 0x00007fcbd0af30b0: _IO_file_overflow + 432
==215590==    at 0x00007fcbd0af1835: _IO_file_xsputn + 229
==215590==    at 0x00007fcbd0ae5541: fwrite + 193
==215590==    at 0x00007fcbd0d9f9b4: std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) + 340
==215590==    at 0x000055a12de05ed6: operator<<(std::ostream&, Simple const&) + 39
==215590==    at 0x000055a12de05824: main + 715
==215590==    at 0x00007fcbd0a860b3: __libc_start_main + 243
==215590==    at 0x000055a12de0544e: _start + 46
==215590== 
==215590== 32 bytes in 1 block(s) are lost, originally allocated at:
==215590==    at 0x00007fcbd0e90dc2: malloc + 53
==215590==    at 0x00007fcbd0d16c29: operator new(unsigned long) + 25
==215590==    at 0x000055a12de057cf: main + 630
==215590==    at 0x00007fcbd0a860b3: __libc_start_main + 243
==215590==    at 0x000055a12de0544e: _start + 46
==215590== 
==215590== LEAK SUMMARY:
==215590==    definitely lost: 1056 bytes in 2 blocks
==215590== 
```

The file is available at https://github.com/romintomasetti/heapusage/commit/e79d4c52b47082d0cf9398cd2a4c62ed4f535c7d.

**Comment by d99kris** [comment]
Hi @romintomasetti - thanks for reporting the issue.

Yes, you are correct. This is unfortunately a known limitation of `heapusage`. The `README.md` also tries to document this:

> While Heapusage has less performance impact than Valgrind, its analysis is less precise. It may report leaks originating from system libraries (e.g. libc functions like print()) that might be free'd when the system library is being cleaned up.

I'd recommend `valgrind` or `AddressSanitizer` / `LeakSanitizer` for more precise logging. I don't have any plans to make `heapusage` handle this type of use case.

As a general guideline (if you still want to use `heapusage`) is to ignore any leak reported where you know you are not allocating memory in your application (e.g. `std::cout`, `printf`, etc).

I will proceed to close this issue.
