### ISSUE TITLE
Detect unmatched delete/free

### ISSUE THREAD

**Issue by romintomasetti** [d99kris/heapusage#8]
Valgrind has also a nice feature (not 100% necessary I agree), which is the detection of unmatched delete/free. For instance, if you allocate with ``new [size]``, you must delete it using ``delete[]``.

**Comment by d99kris** [comment]
Hi @romintomasetti - thanks for reporting. Yes it's a nice feature. Unfortunately it's out-of-scope for `heapusage` which just aims to be a simple `malloc` / `free` tracker and report leaks detected. Even for `c++` the tool just tracks `malloc` / `free`/ etc calls, and I prefer to keep the tracking at that level for `heapusage`.

Thanks for the suggestion though! However I will proceed to close this issue as out-of-scope for the  `heapusage` project.
